apiVersion: v1
kind: PersistentVolume
metadata:
  name: queue-redis-pv-volume
  namespace: microblog-app
  labels:
    type: local
    app: queue-redis
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/queue"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: queue-redis-pv-claim
  namespace: microblog-app
  labels:
    app: queue-redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 1Gi  # Sets volume size