apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-redis
  namespace: microblog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-redis
  template:
    metadata:
      labels:
        app: queue-redis
    spec:
      containers:
        - name: queue-redis
          image: redis:5.0.12
          command: ["redis-server"]
          args: ["--requirepass", "$(SECRET_REQUIREPASS)"]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6379
          env:
            - name: SECRET_REQUIREPASS
              valueFrom:
                secretKeyRef:
                  name: queue-secret
                  key: REQUIREPASS
          volumeMounts:
            - mountPath: /queue
              name: queue-redis-pv-volume
      volumes:
        - name: queue-redis-pv-volume
          persistentVolumeClaim:
            claimName: queue-redis-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: queue-redis
  namespace: microblog-app
  labels:
    app: queue-redis
spec:
  ports:
    - protocol: "TCP"
      port: 6379
      targetPort: 6379
  selector:
    app: queue-redis
  type: NodePort