server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: http://auth:80
          predicates:
            - Path=/oauth2/**,/login
        - id: user
          uri: http://user:80
          predicates:
            - Path=/api/users/**
        - id: post
          uri: http://post:80
          predicates:
            - Path=/api/posts**, /api/posts/**, /api/tags**, /api/tags/**, /api/feed**

management:
  endpoint:
    health:
      probes:
        enabled: true

