server:
  port: 80

spring:
  application:
    name: auth
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true

management:
  endpoint:
    health:
      probes:
        enabled: true