apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: microblog-app
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:0.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /actuator/health/readiness
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 80
              path: /actuator/health/liveness
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: microblog-app
  labels:
    app: gateway
    spring-boot: "true"
spec:
  ports:
    - protocol: "TCP"
      port: 80
  selector:
    app: gateway
  type: LoadBalancer
