apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: microblog-app
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 80
              path: /actuator/health/liveness
            initialDelaySeconds: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: microblog-app
  labels:
    app: user
    spring-boot: "true"
spec:
  ports:
    - protocol: "TCP"
      port: 80
  selector:
    app: user
  type: NodePort
