apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: microblog-app
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: echelon133/user:0.1.0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /actuator/health/readiness
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 80
              path: /actuator/health/liveness
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: SECRET_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-postgres-secret
                  key: POSTGRES_USER
            - name: SECRET_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SECRET_POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: user-postgres-secret
                  key: POSTGRES_DB
            - name: CONFIDENTIAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: confidential-client-secret
                  key: CLIENT_ID
            - name: CONFIDENTIAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: confidential-client-secret
                  key: CLIENT_SECRET
            - name: SECRET_REQUIREPASS
              valueFrom:
                secretKeyRef:
                  name: queue-secret
                  key: REQUIREPASS
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: microblog-app
  labels:
    app: user
    spring-boot: "true"
spec:
  ports:
    - protocol: "TCP"
      port: 80
  selector:
    app: user
  type: NodePort
