apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-postgres
  namespace: microblog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-postgres
  template:
    metadata:
      labels:
        app: report-postgres
    spec:
      containers:
        - name: report-postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: report-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: report-postgres
      volumes:
        - name: report-postgres
          persistentVolumeClaim:
            claimName: report-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: report-postgres
  namespace: microblog-app
  labels:
    app: report-postgres
spec:
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
  selector:
    app: report-postgres
  type: NodePort